version: '3'
services:
  is-nginx:
   container_name: is-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - implementation

  is-mongodb:
    container_name: is-mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  implementation:
    build: ./implementation
    working_dir: /implementation
    volumes:
      - ./implementation:/implementation
      - ~/.m2:/root/.m2
    expose:
      - 8080
    command: mvn clean spring-boot:run
    depends_on:
      - is-mongodb
